Repository KevinKra/futbol, pull requests merged in 2019-10, with the labels that each got.

#1 Update readme with project specific content
  README.md
Labels: documentation

#44 Add github pr template
  docs/pull_request_template.md
Labels: General

#45 Resolve pr template issue, create github directory
  .github/pull_request_template.md
Labels: General

#46 Feature/iteration 1 kevin
  .github/pull_request_template.md
  lib/result.rb
  lib/runner.rb
  lib/stat_tracker.rb
  lib/team.rb
Labels: General, Iteration_1

#48 Feature/iteration 1 kevin
  test/mock_data/mock_games.csv
  test/mock_data/mock_results.csv
  test/mock_data/mock_teams.csv
  test/result_test.rb
  test/stat_tracker_test.rb
  test/team_test.rb
Labels: General, Iteration_1

#49 Feature/iteration 1
  .DS_Store
  Gemfile
  Gemfile.lock
  coverage/.DS_Store
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/.resultset.json.lock
  coverage/assets/.DS_Store
  coverage/assets/0.10.2/application.css
  coverage/assets/0.10.2/application.js
  coverage/assets/0.10.2/colorbox/border.png
  coverage/assets/0.10.2/colorbox/controls.png
  coverage/assets/0.10.2/colorbox/loading.gif
  coverage/assets/0.10.2/colorbox/loading_background.png
  coverage/assets/0.10.2/favicon_green.png
  coverage/assets/0.10.2/favicon_red.png
  coverage/assets/0.10.2/favicon_yellow.png
  coverage/assets/0.10.2/loading.gif
  coverage/assets/0.10.2/magnify.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_flat_75_ffffff_40x100.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_glass_65_ffffff_1x400.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_glass_75_dadada_1x400.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  coverage/assets/0.10.2/smoothness/images/ui-icons_222222_256x240.png
  coverage/assets/0.10.2/smoothness/images/ui-icons_2e83ff_256x240.png
  coverage/assets/0.10.2/smoothness/images/ui-icons_454545_256x240.png
  coverage/assets/0.10.2/smoothness/images/ui-icons_888888_256x240.png
  coverage/assets/0.10.2/smoothness/images/ui-icons_cd0a0a_256x240.png
  coverage/index.html
  data/results.csv
  lib/game.rb
  lib/game_collection.rb
  lib/result.rb
  lib/result_collection.rb
  lib/runner.rb
  lib/stat_tracker.rb
  lib/team.rb
  lib/team_collection.rb
  test/game_collection_test.rb
  test/game_test.rb
  test/mock_data/mock_games.csv
  test/mock_data/mock_results.csv
  test/mock_data/mock_teams.csv
  test/result_test.rb
  test/stat_tracker_test.rb
  test/team_test.rb
  test/test_helper.rb
Labels: Iteration_1

#52 Feature/iteration 2 darren
  coverage/.resultset.json
  coverage/index.html
  lib/game.rb
  lib/game_collection.rb
  lib/result.rb
  lib/result_collection.rb
  lib/stat_tracker.rb
  lib/team_collection.rb
  test/stat_tracker_test.rb
Labels: Iteration_2

#51 Feature/iteration 2 melissa
  lib/game.rb
  lib/game_collection.rb
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Iteration_2

#53 Feature/iteration 2 kevin
  .gitignore
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/index.html
  data/mock_data/mock_games.csv
  data/mock_data/mock_results.csv
  data/mock_data/mock_teams.csv
  lib/result.rb
  lib/stat_tracker.rb
  test/mock_data/mock_results.csv
  test/stat_tracker_test.rb
Labels: Iteration_2

#54 Feature/iteration 2 kevin
  .DS_Store
  .gitignore
  coverage/.DS_Store
  coverage/.last_run.json
  coverage/.resultset.json
  coverage/.resultset.json.lock
  coverage/assets/.DS_Store
  coverage/assets/0.10.2/application.css
  coverage/assets/0.10.2/application.js
  coverage/assets/0.10.2/colorbox/border.png
  coverage/assets/0.10.2/colorbox/controls.png
  coverage/assets/0.10.2/colorbox/loading.gif
  coverage/assets/0.10.2/colorbox/loading_background.png
  coverage/assets/0.10.2/favicon_green.png
  coverage/assets/0.10.2/favicon_red.png
  coverage/assets/0.10.2/favicon_yellow.png
  coverage/assets/0.10.2/loading.gif
  coverage/assets/0.10.2/magnify.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_flat_75_ffffff_40x100.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_glass_65_ffffff_1x400.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_glass_75_dadada_1x400.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png
  coverage/assets/0.10.2/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  coverage/assets/0.10.2/smoothness/images/ui-icons_222222_256x240.png
  coverage/assets/0.10.2/smoothness/images/ui-icons_2e83ff_256x240.png
  coverage/assets/0.10.2/smoothness/images/ui-icons_454545_256x240.png
  coverage/assets/0.10.2/smoothness/images/ui-icons_888888_256x240.png
  coverage/assets/0.10.2/smoothness/images/ui-icons_cd0a0a_256x240.png
  coverage/index.html
  data/mock_data/mock_games.csv
  data/mock_data/mock_results.csv
  data/mock_data/mock_teams.csv
  lib/game.rb
  lib/game_collection.rb
  lib/result.rb
  lib/result_collection.rb
  lib/stat_tracker.rb
  lib/team.rb
  lib/team_collection.rb
  test/game_collection_test.rb
  test/game_test.rb
  test/mock_data/mock_games.csv
  test/mock_data/mock_results.csv
  test/mock_data/mock_teams.csv
  test/result_test.rb
  test/stat_tracker_test.rb
Labels: Iteration_2

#57 Feature/iteration 3 kevin
  data/mock_data/mock_results.csv
  helpers/helpers.rb
  lib/game.rb
  lib/result.rb
  lib/stat_tracker.rb
  lib/team.rb
  test/game_test.rb
  test/result_test.rb
  test/stat_tracker_test.rb
  test/team_test.rb
Labels: Iteration_3

#58 Feature/iteration 3 melissa
  data/mock_data/mock_results.csv
  data/results.csv
  helpers/helpers.rb
  lib/game.rb
  lib/result.rb
  lib/runner.rb
  lib/stat_tracker.rb
  lib/team.rb
  test/game_test.rb
  test/result_test.rb
  test/stat_tracker_test.rb
  test/team_test.rb
Labels: Iteration_3

#59 Feature/iteration 4 kevin
  data/mock_data/mock_games.csv
  lib/game.rb
  lib/result.rb
  lib/stat_tracker.rb
  lib/team.rb
  test/game_test.rb
  test/result_test.rb
  test/stat_tracker_test.rb
  test/team_test.rb
Labels: Iteration_4

#61 Feature/iteration 4
  data/game_teams.csv
  data/mock_data/mock_games.csv
  data/mock_data/mock_results.csv
  lib/game.rb
  lib/result.rb
  lib/runner.rb
  lib/stat_tracker.rb
  lib/team.rb
  test/game_test.rb
  test/result_test.rb
  test/stat_tracker_test.rb
  test/team_test.rb
Labels: Iteration_4

#62 Adds iteration 5 methods
  helpers/helpers.rb
  lib/game.rb
  lib/result.rb
  lib/stat_tracker.rb
  test/stat_tracker_test.rb
Labels: Iteration_5

#63 Feature/iteration 5 melissa
  data/mock_data/mock_games.csv
  data/mock_data/mock_results.csv
  helpers/helpers.rb
  lib/game.rb
  lib/result.rb
  lib/stat_tracker.rb
  test/game_test.rb
  test/result_test.rb
  test/stat_tracker_test.rb
Labels: Iteration_5
